export const ActionTypes = {
    Fetch_PRODUCTS : 'Fetch_PRODUCTS',
    SET_PRODUCTS : ' SET_PRODUCTS' ,
    SELECTED_PRODUCT: '  SELECTED_PRODUCT' ,
    REMOVE_SELECTED_PRODUCT : ' REMOVE_SELECTED_PRODUCT' ,    
}